Repository GitHubNonDev21/caption-this, pull requests merged in 2024-03, with the labels that each got.

#18 Update 06-AmsaleJonah.md
  _slides/06-AmsaleJonah.md
Labels: help wanted

#15 Update 13-paulsuttle.md
  _slides/13-paulsuttle.md
Labels: enhancement

#20 Update 06-AmsaleJonah.md
  _slides/06-AmsaleJonah.md
Labels: question

#22 Update 13-paulsuttle.md
  _slides/13-paulsuttle.md
Labels: enhancement

#12 Update 06-AmsaleJonah.md
  _slides/06-AmsaleJonah.md
Labels: bug
